#!/bin/bash
# Automated Vercel + Railway Configuration Generator
# Generates all config files needed for deployment

set -e

CONFIG_DIR=".automations/configs"
mkdir -p "$CONFIG_DIR"

echo "🔧 Generating Automation Configurations..."

# 1. Vercel Configuration
cat > "$CONFIG_DIR/vercel-config.json" << 'EOF'
{
  "buildCommand": "cd MelodieSpark/apps/web && pnpm run build",
  "outputDirectory": ".next",
  "installCommand": "pnpm install",
  "framework": "nextjs",
  "nodeVersion": "20.x",
  "env": {
    "NEXT_PUBLIC_API_URL": {
      "production": "@railway_api_url"
    }
  },
  "regions": ["sfo1"],
  "buildOutput": "web",
  "publicSource": true,
  "analytics": true,
  "protected": false,
  "autoExposeSystemEnvs": false
}
EOF

echo "✅ Vercel config generated"

# 2. Railway Configuration
cat > "$CONFIG_DIR/railway-config.json" << 'EOF'
{
  "services": [
    {
      "name": "api",
      "dockerfile": "MelodieSpark/apps/api/Dockerfile",
      "startCommand": "npm run start",
      "environment": {
        "NODE_ENV": "production",
        "PORT": "3001"
      },
      "healthCheck": {
        "path": "/health",
        "interval": 30000,
        "timeout": 10000
      },
      "autoDeploy": true,
      "region": "us-west"
    },
    {
      "name": "database",
      "image": "postgres:16-alpine",
      "environment": {
        "POSTGRES_DB": "melodiespark",
        "POSTGRES_USER": "melodiespark"
      }
    },
    {
      "name": "cache",
      "image": "redis:7-alpine",
      "environment": {
        "REDIS_MAXMEMORY": "256mb"
      }
    }
  ]
}
EOF

echo "✅ Railway config generated"

# 3. GitHub Actions Environment
cat > "$CONFIG_DIR/github-env.yml" << 'EOF'
# GitHub Actions Environment Configuration

env:
  NODE_VERSION: "20"
  VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
  VERCEL_PROJECT_ID: "${{ secrets.VERCEL_PROJECT_ID }}"
  RAILWAY_TEAM_ID: "${{ secrets.RAILWAY_TEAM_ID }}"
  
secrets:
  - VERCEL_TOKEN: "Get from https://vercel.com/account/tokens"
  - VERCEL_ORG_ID: "From Vercel project settings"
  - VERCEL_PROJECT_ID: "From Vercel project settings"
  - RAILWAY_TOKEN: "Get from https://railway.app/account/tokens"
  - ANTHROPIC_API_KEY: "Your API key"
  - OPENAI_API_KEY: "Your API key"
EOF

echo "✅ GitHub Actions config generated"

# 4. Environment Template
cat > "$CONFIG_DIR/.env.template" << 'EOF'
# API Keys
ANTHROPIC_API_KEY=sk-...
OPENAI_API_KEY=sk-...

# Environment
NODE_ENV=production

# Database (auto-generated by Railway)
DATABASE_URL=postgresql://user:pass@host:5432/db

# Cache (auto-generated by Railway)
REDIS_URL=redis://host:6379

# JWT
JWT_SECRET=generate-random-string-here

# Frontend API URL (auto-updated after Railway deploy)
NEXT_PUBLIC_API_URL=https://api.railway.app

# Services
QDRANT_URL=http://qdrant:6333
EOF

echo "✅ Environment template generated"

# 5. Monitoring Configuration
cat > "$CONFIG_DIR/monitoring-config.json" << 'EOF'
{
  "healthChecks": [
    {
      "name": "API Health",
      "url": "/health",
      "interval": 300,
      "timeout": 10,
      "alert": true
    },
    {
      "name": "Frontend",
      "url": "/",
      "interval": 600,
      "timeout": 10,
      "alert": false
    },
    {
      "name": "Database",
      "type": "ping",
      "interval": 300,
      "alert": true
    }
  ],
  "alerts": [
    {
      "type": "email",
      "to": "admin@melodiespark.com",
      "onFailure": true
    },
    {
      "type": "slack",
      "webhook": "@slack_webhook_url",
      "onFailure": true
    }
  ],
  "retention": {
    "logs": 30,
    "metrics": 90,
    "backups": 7
  }
}
EOF

echo "✅ Monitoring config generated"

# 6. Automation State Schema
cat > "$CONFIG_DIR/state-schema.json" << 'EOF'
{
  "deployment": {
    "vercel_url": "string",
    "railway_url": "string",
    "deployed_at": "timestamp",
    "deployed_by": "string",
    "commit_hash": "string"
  },
  "services": {
    "api_status": "online|offline|degraded",
    "frontend_status": "online|offline|degraded",
    "database_status": "online|offline",
    "cache_status": "online|offline"
  },
  "monitoring": {
    "last_check": "timestamp",
    "health_score": "0-100",
    "uptime_percentage": "0-100"
  }
}
EOF

echo "✅ State schema generated"

# 7. Rollback Configuration
cat > "$CONFIG_DIR/rollback-config.json" << 'EOF'
{
  "rollback": {
    "automatic": false,
    "on_health_check_failure": false,
    "on_deployment_error": true,
    "max_rollback_age": 86400,
    "keep_versions": 5
  },
  "notification": {
    "slack": true,
    "email": true,
    "pagerduty": false
  }
}
EOF

echo "✅ Rollback config generated"

# 8. Performance Tuning
cat > "$CONFIG_DIR/performance-tuning.json" << 'EOF'
{
  "vercel": {
    "caching": {
      "maxAge": 31536000,
      "staleWhileRevalidate": 86400
    },
    "compressionLevel": 9,
    "bundleAnalysis": true
  },
  "railway": {
    "cpu": "1",
    "memory": "512MB",
    "autoScale": {
      "enabled": true,
      "minReplicas": 1,
      "maxReplicas": 5,
      "targetCPU": 70,
      "targetMemory": 80
    }
  }
}
EOF

echo "✅ Performance tuning config generated"

# Generate summary
cat > "$CONFIG_DIR/README.md" << 'EOF'
# Automation Configurations

All configuration files for automated deployment are stored here.

## Files

- `vercel-config.json` - Vercel deployment settings
- `railway-config.json` - Railway services configuration
- `github-env.yml` - GitHub Actions environment
- `.env.template` - Environment variables template
- `monitoring-config.json` - Health check & monitoring setup
- `state-schema.json` - Deployment state structure
- `rollback-config.json` - Automatic rollback settings
- `performance-tuning.json` - Performance optimization

## Usage

1. Update variables with your values
2. Copy to appropriate deployment targets
3. Run automation scripts

## Next Steps

- Setup GitHub secrets (see github-env.yml)
- Configure monitoring alerts
- Test automated deployment
- Setup backup procedures
EOF

echo "✅ README generated"

# Summary
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ All automation configurations generated successfully!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📁 Location: $CONFIG_DIR/"
echo ""
echo "📋 Generated files:"
ls -1 "$CONFIG_DIR/" | sed 's/^/   ✓ /'
echo ""
echo "🎯 Next steps:"
echo "   1. Review all configurations"
echo "   2. Update with your API keys & settings"
echo "   3. Commit to Git: git add .automations/"
echo "   4. Run: bash automation-orchestrator.sh"
echo ""
